apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: coolersai/go-hello-kub-image:latest
          imagePullPolicy: IfNotPresent  # Используем локальную копию образа
          ports:
            - containerPort: 8082
          env:
            - name: COUNTER_URL
              value: "http://counter-service:8081"