apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: coolersai/go-hello-kub-image:latest
          ports:
            - containerPort: 8082
          env:
           - name: COUNTER_URL
             value: "http://counter-service:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
